#===============================================================#
#======================= VALIDAÇÃO DO MERGE ====================#
#===============================================================#
validacao-pipe:
  stage: Validacao-Pipeline
  image: ubuntu:latest
  script:
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        case "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" in
          "desenvolvimento")
            if [[ "$CI_COMMIT_REF_NAME" =~ ARQ/|FEA/|FIX/|arq/|fea/|fix/ || "$CI_COMMIT_REF_NAME" = "homologacao" ]]; then
                echo "Merge Aprovado :)..."
                exit 0
            else
                echo "Merge inválido."
                exit 1
            fi
          ;;
          "homologacao")
            if [ "$CI_COMMIT_REF_NAME" = "desenvolvimento" ] || [ "$CI_COMMIT_REF_NAME" = "producao" ]; then
                echo "Merge Aprovado :)..."
                exit 0
            else
                echo "Merge inválido."
                exit 1
            fi
          ;;
          "producao")
            if [ "$CI_COMMIT_REF_NAME" = "homolocacao" || "$CI_COMMIT_REF_NAME" =~ HOTFIX/|hotfix/ ]; then
                echo "Merge Aprovado :)..."
                exit 0
            else
                echo "Merge inválido."
                exit 1
            fi
          ;;
          "desenvolvimento-f")
            echo "Merge Aprovado :)..."
            exit 0
          ;;
          "homologacao-f")
            if [ "$CI_COMMIT_REF_NAME" = "tst-f" ]; then
                echo "Merge Aprovado :)..."
                exit 0
            else
                echo "Merge inválido. Merge somente de tst-f para hml-f."
                exit 1
            fi
          ;;
          *)
            echo "Merge inválido. Comunicar a equipe DevOps para suporte."
            exit 1
          ;;
        esac
      else
        echo "Merge inválido. Comunicar a equipe DevOps para suporte."
        exit 1
      fi
  only:
    - merge_requests
  tags:
    - runner-64-177-docker-m2
