#===============================================================#
#========================== SonarQube ==========================#
#===============================================================#
.sonnar:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - desenvolvimento
    - homologacao
    - producao
  tags:
    - runner-64-46-docker
